proc import replace datafile='~/STA 160/Data/OCT12SANDYDIST.csv' out=oct12 dbms=csv;
run;
proc import datafile='~/STA 160/Data/ALLUTC.csv' out=merged dbms=csv;
run;
data oct12;
	set oct12;
	if arrdelay = 'NA' then arrdelay = '.';
	if UTCDepHour = '0' then UTCDepHour = '100';
	if UTCDepHour = '1' then UTCDepHour = '101';
	if UTCDepHour = '2' then UTCDepHour = '102';
	if UTCDepHour = '3' then UTCDepHour = '103';
	if UTCDepHour = '4' then UTCDepHour = '104';
	if UTCDepHour = '5' then UTCDepHour = '105';
	if UTCDepHour = '6' then UTCDepHour = '106';
	if UTCDepHour = '7' then UTCDepHour = '107';
	if UTCDepHour = '8' then UTCDepHour = '108';
	if UTCDepHour = '9' then UTCDepHour = '109';
	if UTCDepHour = '10' then UTCDepHour = '110';
	if UTCDepHour = '11' then UTCDepHour = '111';
	if UTCDepHour = '12' then UTCDepHour = '112';
	if UTCDepHour = '13' then UTCDepHour = '113';
	if UTCDepHour = '14' then UTCDepHour = '114';
	if UTCDepHour = '15' then UTCDepHour = '115';
	if UTCDepHour = '16' then UTCDepHour = '116';
	if UTCDepHour = '17' then UTCDepHour = '117';
	if UTCDepHour = '18' then UTCDepHour = '118';
	if UTCDepHour = '19' then UTCDepHour = '119';
	if UTCDepHour = '20' then UTCDepHour = '120';
	if UTCDepHour = '21' then UTCDepHour = '121';
	if UTCDepHour = '22' then UTCDepHour = '122';
	if UTCDepHour = '23' then UTCDepHour = '123';
	if UTCDepHour = '24' then UTCDepHour = '124';
	arrdelaynum = input(arrdelay,BEST.);
run;
data aug05;
	set merged;
	if year ne '2005' then delete;
	if arrdelay = 'NA' then arrdelay = '.';
	if UTCDepHour = '0' then UTCDepHour = '100';
	if UTCDepHour = '1' then UTCDepHour = '101';
	if UTCDepHour = '2' then UTCDepHour = '102';
	if UTCDepHour = '3' then UTCDepHour = '103';
	if UTCDepHour = '4' then UTCDepHour = '104';
	if UTCDepHour = '5' then UTCDepHour = '105';
	if UTCDepHour = '6' then UTCDepHour = '106';
	if UTCDepHour = '7' then UTCDepHour = '107';
	if UTCDepHour = '8' then UTCDepHour = '108';
	if UTCDepHour = '9' then UTCDepHour = '109';
	if UTCDepHour = '10' then UTCDepHour = '110';
	if UTCDepHour = '11' then UTCDepHour = '111';
	if UTCDepHour = '12' then UTCDepHour = '112';
	if UTCDepHour = '13' then UTCDepHour = '113';
	if UTCDepHour = '14' then UTCDepHour = '114';
	if UTCDepHour = '15' then UTCDepHour = '115';
	if UTCDepHour = '16' then UTCDepHour = '116';
	if UTCDepHour = '17' then UTCDepHour = '117';
	if UTCDepHour = '18' then UTCDepHour = '118';
	if UTCDepHour = '19' then UTCDepHour = '119';
	if UTCDepHour = '20' then UTCDepHour = '120';
	if UTCDepHour = '21' then UTCDepHour = '121';
	if UTCDepHour = '22' then UTCDepHour = '122';
	if UTCDepHour = '23' then UTCDepHour = '123';
	if UTCDepHour = '24' then UTCDepHour = '124';
	arrdelaynum = input(arrdelay,BEST.);
run;
data sept08;
	set merged;
	if year ne '2008' then delete;
	if arrdelay = 'NA' then arrdelay = '.';
	if UTCDepHour = '0' then UTCDepHour = '100';
	if UTCDepHour = '1' then UTCDepHour = '101';
	if UTCDepHour = '2' then UTCDepHour = '102';
	if UTCDepHour = '3' then UTCDepHour = '103';
	if UTCDepHour = '4' then UTCDepHour = '104';
	if UTCDepHour = '5' then UTCDepHour = '105';
	if UTCDepHour = '6' then UTCDepHour = '106';
	if UTCDepHour = '7' then UTCDepHour = '107';
	if UTCDepHour = '8' then UTCDepHour = '108';
	if UTCDepHour = '9' then UTCDepHour = '109';
	if UTCDepHour = '10' then UTCDepHour = '110';
	if UTCDepHour = '11' then UTCDepHour = '111';
	if UTCDepHour = '12' then UTCDepHour = '112';
	if UTCDepHour = '13' then UTCDepHour = '113';
	if UTCDepHour = '14' then UTCDepHour = '114';
	if UTCDepHour = '15' then UTCDepHour = '115';
	if UTCDepHour = '16' then UTCDepHour = '116';
	if UTCDepHour = '17' then UTCDepHour = '117';
	if UTCDepHour = '18' then UTCDepHour = '118';
	if UTCDepHour = '19' then UTCDepHour = '119';
	if UTCDepHour = '20' then UTCDepHour = '120';
	if UTCDepHour = '21' then UTCDepHour = '121';
	if UTCDepHour = '22' then UTCDepHour = '122';
	if UTCDepHour = '23' then UTCDepHour = '123';
	if UTCDepHour = '24' then UTCDepHour = '124';
	if dayofmonth = '1' then dayofmonth = '101';
	if dayofmonth = '2' then dayofmonth = '102';
	if dayofmonth = '3' then dayofmonth = '103';
	if dayofmonth = '4' then dayofmonth = '104';
	if dayofmonth = '5' then dayofmonth = '105';
	if dayofmonth = '6' then dayofmonth = '106';
	if dayofmonth = '7' then dayofmonth = '107';
	if dayofmonth = '8' then dayofmonth = '108';
	if dayofmonth = '9' then dayofmonth = '109';
	if dayofmonth = '10' then dayofmonth = '110';
	if dayofmonth = '11' then dayofmonth = '111';
	if dayofmonth = '12' then dayofmonth = '112';
	if dayofmonth = '13' then dayofmonth = '113';
	if dayofmonth = '14' then dayofmonth = '114';
	if dayofmonth = '15' then dayofmonth = '115';
	arrdelaynum = input(arrdelay,BEST.);
run;
/* Arrival Delay Plot */
proc sgplot data=oct12;
	title "Arrival Delay by Day and Hour";
	xaxis label="Day of Month" type=discrete discreteorder=formatted;
	yaxis label="Departure Hour (UTC)" type=discrete discreteorder=formatted;
	label arrdelaynum = "Arrival Delay (mins)";
	heatmap x=dayofmonth y=UTCDepHour / name="heatmap" colorResponse=arrdelaynum colorstat=mean
	discretex discretey colormodel=(green white red);
run;
proc sgplot data=sept08;
	title "Arrival Delay by Day and Hour";
	xaxis label="Day of Month" type=discrete discreteorder=formatted;
	yaxis label="Departure Hour (UTC)" type=discrete discreteorder=formatted;
	label arrdelaynum = "Arrival Delay (mins)";
	heatmap x=dayofmonth y=UTCDepHour / name="heatmap" colorResponse=arrdelaynum colorstat=mean
	discretex discretey colormodel=(green white red);
run;
proc sgplot data=aug05;
	title "Arrival Delay by Day and Hour";
	xaxis label="Day of Month" type=discrete discreteorder=formatted;
	yaxis label="Departure Hour (UTC)" type=discrete discreteorder=formatted;
	label arrdelaynum = "Arrival Delay (mins)";
	heatmap x=dayofmonth y=UTCDepHour / name="heatmap" colorResponse=arrdelaynum colorstat=mean
	discretex discretey colormodel=(green white red);
run;
/* Cancellation Plot */
proc sgplot data=oct12;
	xaxis label="Day of Month";
	yaxis label="Distance to Storm";
	title "Cancellation Frequency by Day and Distance";
	heatmap x=DayofMonth y=DepDistanceToStorm / freq=cancelled
    Colormodel=(lightsalmon maroon);
run;
proc sgplot data=sept08;
	xaxis label="Day of Month";
	yaxis label="Distance to Storm";
	title "Cancellation Frequency by Day and Distance";
	heatmap x=DayofMonth y=DepDistanceToStorm / freq=cancelled
    Colormodel=(lightsalmon maroon);
run;
proc sgplot data=aug05;
	xaxis label="Day of Month";
	yaxis label="Distance to Storm";
	title "Cancellation Frequency by Day and Distance";
	heatmap x=DayofMonth y=DepDistanceToStorm / freq=cancelled
    Colormodel=(lightsalmon maroon);
run;
