proc import replace datafile='~/STA 160/Data/Sept 2008.csv' out=sept08 dbms=csv;
run;
proc contents varnum;
run;
data sept08;
	set sept08;
	DepTimeAdj = input(DepTime,HHMM.);
	ArrTimeAdj = input(ArrTime,HHMM.);
	drop DepTime ArrTime;
	rename DepTimeAdj = DepTime ArrTimeAdj = ArrTime;
run;
data airports;
	infile '~/STA 160/Data/airports.dat' dlm=',' dsd;
	input id name $ city $ country $ origin $ icao $ lat long alt offset $ dst $ dstbase $ type $ source $;
	drop id;
run;
proc sort data=airports;
	by origin;
run;
proc sort data=sept08;
	by origin;
run;
data sept08;
	merge sept08 (in = insept08) airports (in = inairports);
	by origin;
	if insept08 and inairports;
	drop name city country icao dst dstbase type source;
	rename lat=DepLat long=DepLong alt=DepAlt offset=DepOffset;
run;
proc print data=sept08(obs=15);
run;
data sept08;
	set sept08;
	DepOffsetRev = DepOffset * 100 * -1;
	DepUTC = DepTime + DepOffsetRev;
run;
data airports;
	set airports;
	rename origin = dest;
run;
proc sort data=airports;
	by dest;
run;
proc sort data=sept08;
	by dest;
run;
data sept08;
	merge sept08 (in = insept08) airports (in = inairports);
	by dest;
	if insept08 and inairports;
	drop name city country icao dst dstbase type source;
	rename lat=ArrLat long=ArrLong alt=ArrAlt offset=ArrOffset;
run;
data sept08;
	set sept08;
	ArrOffsetRev = ArrOffset * 100 * -1;
	ArrUTC = ArrTime + ArrOffsetRev;
run;
